<a href="https://colab.research.google.com/github/LQDJerry/MachLearn/blob/main/BackProp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Back Propogation 

In [151]:
#import libraries needed
import numpy as np
import math
import random
import sklearn
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import pandas as pd

Setting up what is given:

In [152]:
data = [((0,0),0),((0,1),1),((1,0),1),((1,1),0)]
trainingData = [((1,0,0),0),((1,0,1),1),((1,1,0),1),((1,1,1),0)]

Setting up the functions we will be using:


In [153]:

#Sigmoid function:

def G(x):
    return (1.0/(1.0+math.exp(-x)))



In [154]:

#Classsification function:

def classsification(Y):
    return [1 if y > 0.5 else 0 for y in Y]


In [155]:

#F(W, X) function:

def F(W, X):
    return sum([w*x for w, x in zip(W, X)])
    

In [156]:

#Prediction Function

def pred(model, x):
  w1 = model[0]
  w2 = model[1]
  v1 = model[2]
  z1 = sigmoid(F(w1, x))
  z2 = sigmoid(F(w2, x))
  Z = (1, z1, z2)
  y = sigmoid(F(v1,Z))
  return y
  

In [157]:
#Randomize Function

def rand0():
  return np.random.uniform(-1,1,3)


We need to randomize the weights:

In [158]:

w1 = rand0()

print(w1)


[ 0.00806788 -0.94939626  0.27771285]


In [159]:

w2 = rand0()

print(w2)


[-0.48397683 -0.25810198  0.38063602]


In [160]:
v1 = rand0()

print(v1)


[-0.81457648  0.93190481 -0.55193472]


In [161]:
 model = [w1,w2,v1]

print("This is the randomized model: ", model)


This is the randomized model:  [array([ 0.00806788, -0.94939626,  0.27771285]), array([-0.48397683, -0.25810198,  0.38063602]), array([-0.81457648,  0.93190481, -0.55193472])]


Being Training Data:


In [162]:
alpha = 0.3

In [163]:
def backProp(model, data, reps, learnRate, sqrErr, accScr):

  w1 = model[0]
  w2 = model[1]
  v1 = model[2]

  for i in range(reps):
    np.random.shuffle(data)

    if (i%420) == 0:
    #checking every 420 epochs
      dataCopy = data
      R = [r for ((x1,x2),r) in dataCopy]
      X = [(1,x1,x2) for ((x1,x2),r) in dataCopy]

      predY = [pred([w1, w2, v1], x) for x in X]
      sqrErr.append(sum([pow(r-y,2) for (r,y) in zip(R, predY)]))
      calssify = classsification(predY)
      accScr.append(sklearn.metrics.accuracy_score(R, calssify))

    for (x, r) in data:
      z1 = G(F(w1, x))
      z2 = G(F(w2, x))
      Z = (1, z1, z2)
      y = G(F(v1,Z))
      deltV = [learnRate * (r - y) * z for z in Z]
      deltW1 = [learnRate * (r - y) * v1[1] * z1 * (1 - z1) * xi for xi in x]
      deltW2 = [learnRate * (r - y) * v1[2] * z2 * (1 - z2) * xi for xi in x]

      v1 = [v + dv for (v, dv) in zip(v1, deltV)]
      w1 = [w + dw for (w, dw) in zip(w1, deltW1)]
      w2 = [w + dw for (w, dw) in zip(w2, deltW2)]

  return [w1,w2,v1]







In [164]:
sqrdError = []
accuracyScore = []

In [165]:
model = backProp(model, data, 180000, alpha, sqrdError, accuracyScore)

print("These are the final weights: ", model)

These are the final weights:  [[3.2779448619828035, -15.511287656507756], [-6.470427600973539, -13.45742841219492], [0.012994567550432212, 9.83589385975187, -28.023453679732327]]


In [171]:
print("Data Given:", data)
predictedY = [pred(model, x) for x in [(1,x1,x2) for ((x1,x2),r) in data]]
print("Predictions for Y:", predictedY)
print("Classification Predictions:", classsification(predictedY))

Data Given: [((1, 1), 0), ((1, 0), 1), ((0, 0), 0), ((0, 1), 1)]
Predictions for Y: [0.5032605442048077, 0.5032605442048077, 0.9999211722184299, 0.9999211722184299]
Classification Predictions: [1, 1, 1, 1]


In [172]:
print(sqrdError)
print(accuracyScore)

[1.0952951373350526, 1.325526268135858, 1.4433799584594889, 1.4680253164618424, 1.477680505889463, 1.4833220834819052, 1.4859943677388383, 1.4882902847966701, 1.4900915947277686, 1.4912081684884573, 1.4920570516350593, 1.4932151747593179, 1.4938863410027314, 1.4940256493274935, 1.4947041414865487, 1.494957284887905, 1.4952283529709824, 1.4955394512346742, 1.49580875531169, 1.4961580324535393, 1.496430560582457, 1.4964506277035226, 1.4968748301381045, 1.496823716511234, 1.4969176858832451, 1.4970578153781444, 1.4973404665702938, 1.4972809643752898, 1.4973861938793602, 1.4974858372675128, 1.4975634674127183, 1.4978126894676964, 1.4979721898764982, 1.4978009237582781, 1.4979552029301133, 1.4979328538095908, 1.498128239241508, 1.498049631668135, 1.498184033349688, 1.498154181414865, 1.4982066308710702, 1.4983672038744433, 1.4985024833717038, 1.4983924842211498, 1.4986067468552347, 1.4984449432956666, 1.498466876536682, 1.4985123859180651, 1.4987006669674678, 1.4985388702814422, 1.498653998

In [180]:
print("The 5 different initial models:", "\n")
models = []
for i in range(5):
  w1 = rand0()
  w2 = rand0()
  v1 = rand0()
  model = [w1,w2, v1]
  models.append(model)
  print(str(i + 1) + ":",np.array(model), "\n")

The 5 different initial models: 

1: [[ 0.766257    0.777711    0.6596284 ]
 [ 0.12814543 -0.52533557  0.92007623]
 [-0.57397233 -0.15757508 -0.61211064]] 

2: [[ 0.70507421  0.90778512  0.14117467]
 [ 0.52392923  0.82425554 -0.34385842]
 [ 0.22330176  0.16490873  0.8045206 ]] 

3: [[ 0.28119598 -0.88644177 -0.23101747]
 [-0.60568366  0.74912884  0.41672789]
 [-0.07680193  0.79937368 -0.75600987]] 

4: [[ 0.41468822  0.5357324  -0.87523009]
 [ 0.2762068   0.29037193  0.98615254]
 [ 0.47758617 -0.47014528 -0.77834638]] 

5: [[-0.90859207  0.72805053 -0.43689766]
 [-0.5708687  -0.05499418  0.4062857 ]
 [ 0.60558485 -0.71052988 -0.09662034]] 



In [181]:
print("The 5 final models: ", "\n")
squaredError = [[] for i in range(len(models))]
for i, model in enumerate(models):
  models[i] = backProp(model, data, 180000, alpha, sqrdError, accuracyScore)

for i, model in enumerate(models):
  print(str(i + 1) + ":", "\n", np.array(model), "\n")

The 5 final models:  

1: 
 [list([12.02845958713489, 12.028469454848691])
 list([-12.164249514740463, -12.16427373701881])
 list([-8.84051505335107, 9.481238355427005, -11.420199339275023])] 

2: 
 [list([0.9367199933905918, 0.9363969173293746])
 list([9.831894842318272, 9.831961986686165])
 list([1.619168998212204, -87.03221001763819, 67.63634197687695])] 

3: 
 [list([3.281296743610591, -15.5147897532258])
 list([-6.461327622226995, -13.455392300565245])
 list([0.025507218575624612, 9.833595342054085, -28.016244876911163])] 

4: 
 [list([-0.9498706399634854, -0.9487398580179448])
 list([-9.831457323982772, -9.830468140822004])
 list([-17.359891410477097, 86.44571134715866, -67.64327026132486])] 

5: 
 [list([-15.495758582285848, 3.2686691898426856])
 list([-13.457213074626456, -6.519976137936327])
 list([-0.006051221300400672, 9.837277574224544, -28.02487929700271])] 



/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  import sys
